; THIS IS THE MODIFIED SEPTEMBER ATARI 400/800 COMPUTER OPERATING
; SYSTEM LISTING. MODIFIED TO ASSEMBLE ON THE MICROTEC CROSS
; ASSEMBLER.
; THIS VERSION IS THE ONE WHICH WAS BURNED INTO ROM.
; THERE IS A RESIDUAL PIECE OF CODE WHICH IS FOR LNBUG. THIS
; IS AT LOCATION $9000 WHICH IS NOT IN ROM.
;
; THIS IS THE REVISION B EPROM VERSION
		  .PAGE
;
;
;		 COLLEEN OPERATING SYSTEM EQUATE FILE
;
;		 NTSC/PAL ASSEMBLY FLAG
;
PALFLG  =		 0			  ;0 = NTSC	1 = PAL
;
;
;		 MODULE ORIGIN TABLE
;
CHRORG  =		 $E000		 ;CHARACTER SET
VECTBL  =		 $E400		 ;VECTOR TABLE
VCTABL  =		 $E480		 ;RAM VECTOR INITIAL VALUE TABLE
CIOORG  =		 $E4A6		 ;CENTRAL I/O HANDLER
INTORG  =		 $E6D5		 ;INTERRUPT HANDLER
SIOORG  =		 $E944		 ;SERIAL I/O DRIVER
DSKORG  =		 $EDEA		 ;DISK HANDLER
PRNORG  =		 $EE78		 ;PRINTER HANDLER
CASORG  =		 $EF41		 ;CASSETTE HANDLER
MONORG  =		 $F0E3		 ;MONITOR/POWER UP MODULE
KBDORG  =		 $F3E4		 ;KEYBOARD/DISPLAY HANDLER
;
;
;
;
;		VECTOR TABLE
;
;HANDLER ENTRY POINTS ARE CALLED OUT IN THE FOLLOWING VECTOR
;TABLE. THESE ARE THE ADDRESSES MINUS ONE.
;
;
;EXAMPLE FOR EDITOR
;
;	 E400		 OPEN
;		 2		 CLOSE
;		 4		 GET
;		 6		 PUT
;		 8		 STATUS
;		 A		 SPECIAL
;		 C		 JUMP TO POWER ON INITIALIZATION ROUTINE
;		 F		 NOT USED
;
;
EDITRV  =		 $E400		 ;EDITOR
SCRENV  =		 $E410		 ;TELEVISION SCREEN
KEYBDV  =		 $E420		 ;KEYBOARD
PRINTV  =		 $E430		 ;PRINTER
CASETV  =		 $E440		 ;CASSETTE
;
;		 JUMP VECTOR TABLE
;
;THE FOLLOWING IS A TABLE OF JUMP INSTRUCTIONS
;TO VARIOUS ENTRY POINTS IN THE OPERATING SYSTEM.
;
DISKIW  =		 $E450		 ;DISK INITIALIZATION
DSKINV  =		 $E453		 ;DISK INTERFACE
CIOV	 =		 $E456		 ;CENTRAL INPUT OUTPUT ROUTINE
SIOV	 =		 $E459		 ;SERIAL INPUT OUTPUT ROUTINE
SETVBV  =		 $E45C		 ;SET SYSTEM TIMERS ROUTINE
SYSVBV  =		 $E45F		 ;SYSTEM VERTICAL BLANK CALCULATIONS
XITVBV  =		 $E462		 ;EXIT VERTICAL BLANK CALCULATIONS
SIOINV  =		 $E465		 ;SERIAL, INPUT OUTPUT INITIALIZATION
SENDEV  =		 $E468		 ;SEND ENABLE ROUTINE
INTINV  =		 $E46B		 ;INTERRUPT HANDLER INITIALIZATION
CIOINV  =		 $E46E		 ;CENTRAL INPUT OUTPUT INITIALIZATION
BLKBDV  =		 $E471		 ;BLACKBOARD MODE
WARMSV  =		 $E474		 ;WARM START ENTRY POINT
COLDSV  =		 $E477		 ;COLD START ENTRY POINT
RBLOKV  =		 $E47A		 ;CASSETTE READ BLOCK ENTRY POINT VECTOR
CSOPIV  =		 $E47D		 ;CASSETTE OPEN FOR INPUT VECTOR
;VCTABL = $E480
;
;
; OPERATING SYSTEM EQUATES
;
; COMMAND CODES FOR IOCB
OPEN	 =		 3			  ;OPEN FOR INPUT/OUTPUT
GETREC  =		 5			  ;GET RECORD (TEXT)
GETCHR  =		 7			  ;GET CHARACTER(S)
PUTREC  =		 9			  ;PUT RECORD (TEXT)
PUTCHR  =		 $B			 ;PUT CHARACTER(S)
CLOSE	=		 $C			 ;CLOSE DEVICE
STATIS  =		 $D			 ;STATUS REQUEST
SPECIL  =		 $E			 ;BEGINNING OF SPECIAL ENTRY COMMANDS
;
; SPECIAL ENTRY COMMANDS
DRAWLN  =		 $11			;DRAW LINE
FILLIN  =		 $12			;DRAW LINE WITH RIGHT FILL
RENAME  =		 $20			;RENAME DISK FILE
DELETE  =		 $21			;DELETE DISK FILE
FORMAT  =		 $22			;FORMAT
LOCKFL  =		 $23			;LOCK FILE TO READ ONLY
UNLOCK  =		 $24			;UNLOCK LOCKED FILE
POINT	=		 $25			;POINT SECTOR
NOTE	 =		 $26			;NOTE SECTOR
IOCFRE  =		 $FF			;IOCB "FREE"
;
; AUX1 EQUATES
; () INDICATES WHICH DEVICES USE BIT
APPEND  =		 $1			 ;OPEN FOR WRITE APPEND (D), OR SCREEN READ (
DIRECT  =		 $2			 ;OPEN FOR DIRECTORY ACCESS (D)
OPNIN	=		 $4			 ;OPEN FOR INPUT (ALL DEVICES)
OPNOT	=		 $8			 ;OPEN FOR OUTPUT (ALL DEVICES)
OPNINO  =		 OPNIN+OPNOT ;OPEN FOR INPUT AND OUTPUT (ALL DEVICES)
MXDMOD  =		 $10			;OPEN FOR MIXED MODE (E,S)
INSCLR  =		 $20			;OPEN WITHOUT CLEARING SCREEN (E,S)
;
; DEVICE NAMES
SCREDT  =		 'E			 ;SCREEN EDITOR (R/W)
KBD	  =		 'K			 ;KEYBOARD (R ONLY)
D1SPLY  =		 'S			 ;SCREEN DISPLAY (R/W)
PRINTR  =		 'P			 ;PRINTER (W ONLY)
CASSET  =		 'C			 ;CASSETTE
MODEM	=		 'M			 ;MODEM
DISK	 =		 'D			 ;DISK (R/W)
;
; SYSTEM EOL (CARRIAGE RETURN)
CR		=		 $9B
;
;
;		 OPERATING SYSTEM STATUS CODES
;
SUCCES  =		 $01			;SUCCESSFUL OPERATION
;
BRKABT  =		 $80			;BREAK KEY ABORT
PRVOPN  =		 $81			;IOCB ALREADY OPEN
NONDEV  =		 $82			;NON-EXISTANT DEVICE
WRONLY  =		 $83			;IOCB OPENED FOR WRITE ONLY
NVALID  =		 $84			;INVALID COMMAND
NOTOPN  =		 $85			;DEVICE OR FILE NOT OPEN
BADIOC  =		 $86			;INVALID IOCB NUMBER
RDONLY  =		 $87			;IOCB OPENED FOR READ ONLY
EOFERR  =		 $88			;END OF FILE
TRNRCD  =		 $89			;TRUNCATED RECORD
TIMOUT  =		 $8A			;PERIPHERAL DEVICE TIME OUT
DNACK	=		 $8B			;DEVICE DOES NOT ACKNOWLEDGE COMMAND
FRMERR  =		 $8C			;SERIAL BUS FRAMING ERROR
CRSROR  =		 $8D			;CURSOR OVERRANCE
OVRRUN  =		 $8E			;SERIAL BUS DATA OVERRUN
CHKERR  =		 $8F			;SERIAL BUS CHECKSUM ERROR
;
DERROR  =		 $90			;PERIPHERAL DEVICE ERROR (OPERATION NOT COMP
BADMOD  =		 $91			;BAD SCREEN MODE NUMBER
FNCNOT  =		 $92			;FUNCTION NOT IMPLEMENTED IN HANDLER
SCRMEM  =		 $93			;INSUFICIENT MEMORY FOR SCREEN MODE
;
;
;
;
;
;
;		 PAGE ZERO RAM ASSIGNMENTS
;
		  *=$0000
LINZBS: .RES	 2			  ;LINBUG RAM (WILL BE REPLACED BY MONITOR RAM
;
; THESE LOCATIONS ARE NOT CLEARED
CASINI: .RES	 2			  ;CASSETTE INIT LOCATION
RAMLO:  .RES	 2			  ;RAM POINTER FOR MEMORY TEST
TRAMSZ: .RES	 1			  ;TEMPORARY REGISTER FOR RAM SIZE
TSTDAT: .RES	 1			  ;RAM TEST DATA REGISTER
;
; CLEARED ON COLOSTART ONLY
WARMST: .RES	 1			  ;WARM START FLAG
BOOT?:  .RES	 1			  ;SUCCESSFUL BOOT FLAG
DOSVEC: .RES	 2			  ;DISK SOFTWARE START VECTOR
DOSINI: .RES	 2			  ;DISK SOFTWARE INIT ADDRESS
APPMHI: .RES	 2			  ;APPLICATIONS MEMORY HI LIMIT
;
; CLEARED ON COLD OR WARM START
INTZBS  =*						;INTERRUPT HANDLER
POKMSK: .RES	 1			  ;SYSTEM MASK FOR POKEY IRQ ENABLE
BRKKEY: .RES	 1			  ;BREAK KEY FLAG
RTCLOK: .RES	 3			  ;REAL TIME CLOCK (IN 16 MSEC UNITS)
;
BUFADR: .RES	 2			  ;INDIRECT BUFFER ADDRESS REGISTER
;
ICCOMT: .RES	 1			  ;COMMAND FOR VECTOR
;
DSKFMS: .RES	 2			  ;DISK FILE MANAGER POINTER
DSKUTL: .RES	 2			  ;DISK UTILITIES POINTER
;
PTIMOT: .RES	 1			  ;PRINTER TIME OUT REGISTER
PBPNT:  .RES	 1			  ;PRINT BUFFER POINTER
PBUFSZ: .RES	 1			  ;PRINT BUFFER SIZE
PTEMP:  .RES	 1			  ;TEMPORARY REGISTER
;
ZIOCB	=*						;ZERO PAGE I/O CONTROL BLOCK
IOCBSZ  =		 16			 ;NUMBER OF BYTES PER IOCB
MAXIOC  =		 8*IOCBSZ	 ;LENGTH OF THE IOCB AREA
IOCBAS  =*
ICHIDZ: .RES	 1			  ;HANDLER INDEX NUMBER (FF = IOCB FREE)
ICDNOZ: .RES	 1			  ;DEVICE NUMBER (DRIVE NUMBER)
ICCOMZ: .RES	 1			  ;COMMAND CODE
ICSTAZ: .RES	 1			  ;STATUS OF LAST IOCB ACTION
ICBALZ: .RES	 1			  ;BUFFER ADDRESS LOW BYTE
ICBAHZ: .RES	 1
ICPTLZ: .RES	 1			  ;PUT BYTE ROUTINE ADDRESS - 1
ICPTHZ: .RES	 1
ICBLLZ: .RES	 1			  ;BUFFER LENGTH LOW BYTE
ICBLHZ: .RES	 1
ICAX1Z: .RES	 1			  ;AUXILIARY INFORMATION FIRST BYTE
ICAX2Z: .RES	 1
ICSPRZ: .RES	 4			  ;TWO SPARE BYTES (CIO LOCAL USE)
ICIDNO  =		 ICSPRZ+2	 ;IOCB NUMBER X 16
CIOCHR  =		 ICSPRZ+3	 ;CHARACTER BYTE FOR CURRENT OPERATION
;
STATUS: .RES	 1			  ;INTERNAL STATUS STORAGE
CHKSUM: .RES	 1			  ;CHECKSUM (SINGLE BYTE SUM WITH CARRY)
BUFRLO: .RES	 1			  ;POINTER TO DATA BUFFER (LO BYTE)
