BRKKEY: .RES	 1			  ;BREAK KEY FLAG
RTCLOK: .RES	 3			  ;REAL TIME CLOCK (IN 16 MSEC UNITS)
;
BUFADR: .RES	 2			  ;INDIRECT BUFFER ADDRESS REGISTER
;
ICCOMT: .RES	 1			  ;COMMAND FOR VECTOR
;
DSKFMS: .RES	 2			  ;DISK FILE MANAGER POINTER
DSKUTL: .RES	 2			  ;DISK UTILITIES POINTER
;
PTIMOT: .RES	 1			  ;PRINTER TIME OUT REGISTER
PBPNT:  .RES	 1			  ;PRINT BUFFER POINTER
PBUFSZ: .RES	 1			  ;PRINT BUFFER SIZE
PTEMP:  .RES	 1			  ;TEMPORARY REGISTER
;
ZIOCB	=*						;ZERO PAGE I/O CONTROL BLOCK
IOCBSZ  =		 16			 ;NUMBER OF BYTES PER IOCB
MAXIOC  =		 8*IOCBSZ	 ;LENGTH OF THE IOCB AREA
IOCBAS  =*
ICHIDZ: .RES	 1			  ;HANDLER INDEX NUMBER (FF = IOCB FREE)
ICDNOZ: .RES	 1			  ;DEVICE NUMBER (DRIVE NUMBER)
ICCOMZ: .RES	 1			  ;COMMAND CODE
ICSTAZ: .RES	 1			  ;STATUS OF LAST IOCB ACTION
ICBALZ: .RES	 1			  ;BUFFER ADDRESS LOW BYTE
ICBAHZ: .RES	 1
ICPTLZ: .RES	 1			  ;PUT BYTE ROUTINE ADDRESS - 1
ICPTHZ: .RES	 1
ICBLLZ: .RES	 1			  ;BUFFER LENGTH LOW BYTE
ICBLHZ: .RES	 1
ICAX1Z: .RES	 1			  ;AUXILIARY INFORMATION FIRST BYTE
ICAX2Z: .RES	 1
ICSPRZ: .RES	 4			  ;TWO SPARE BYTES (CIO LOCAL USE)
ICIDNO  =		 ICSPRZ+2	 ;IOCB NUMBER X 16
CIOCHR  =		 ICSPRZ+3	 ;CHARACTER BYTE FOR CURRENT OPERATION
;
STATUS: .RES	 1			  ;INTERNAL STATUS STORAGE
CHKSUM: .RES	 1			  ;CHECKSUM (SINGLE BYTE SUM WITH CARRY)
BUFRLO: .RES	 1			  ;POINTER TO DATA BUFFER (LO BYTE)
BUFRHI: .RES	 1			  ;POINTER TO DATA BUFFER (HI BYTE)
BFENLO: .RES	 1			  ;NEXT BYTE PAST END OF THE DATA BUFFER (LO B
BFENHI: .RES	 1			  ;NEXT BYTE PAST END OF THE DATA BUFFER (HI B
CRETRY: .RES	 1			  ;NUMBER OF COMMAND FRAME RETRIES
DRETRY: .RES	 1			  ;NUMBER OF DEVICE RETRIES
BUFRFL: .RES	 1			  ;DATA BUFFER FULL FLAG
RECVDN: .RES	 1			  ;RECEIVE DONE FLAG
XMTDON: .RES	 1			  ;TRANSMISSION DONE FLAG
CHKSNT: .RES	 1			  ;CHECKSUM SENT FLAG
NOCKSM: .RES	 1			  ;NO CHECKSUM FOLLOWS DATA FLAG
;
;
BPTR:	.RES	 1
FTYPE:  .RES	 1
FEOF:	.RES	 1
FREQ:	.RES	 1
SOUNDR: .RES	 1			  ;NOISY I/O FLAG. (ZERO IS QUIET)
CRITIC: .RES	 1			  ;DEFINES CRITICAL SECTION (CRITICAL IF NON-Z
;
FMSZPG: .RES	 7			  ;DISK FILE MANAGER SYSTEM ZERO PAGE
;
;
CKEY:	.RES	 1			  ;FLAG SET WHEN GAME START PRESSED
CASSBT: .RES	 1			  ;CASSETTE BOOT FLAG
DSTAT:  .RES	 1			  ;DISPLAY STATUS
;
ATRACT: .RES	 1			  ;ATRACT FLAG
DRKMSK: .RES	 1			  ;DARK ATRACT MASK
COLRSH: .RES	 1			  ;ATRACT COLOR SHIFTER (EOR'ED WITH PLAYFIELD
;
